name=input("Enter your name :")
branch=input("Enter your branch :")
gender=input("Enter your gender :")
college=input("Enter your college name :")
age=input("Enter your age :")
print(name)
print(branch)
print(gender)
print(college)
print(age)
